#!/bin/bash
set -e

echo " Building MonExamen for Render..."
echo ""

# Verify Python availability
echo " Python version:"
python3 --version
echo ""

# Install Backend dependencies
echo " Installing Backend dependencies..."
if [ -f "Backend/requirements.txt" ]; then
    pip install --no-cache-dir -r Backend/requirements.txt
    echo " Backend dependencies installed successfully!"
else
    echo " Backend/requirements.txt not found!"
    exit 1
fi

echo ""

# Generate Frontend config.js with BACKEND_URL injected from Render env var
echo "️  Generating Frontend/config.js..."
if [ -n "$BACKEND_URL" ]; then
    cat > Frontend/config.js <<EOF
/* Auto-generated by build.sh — DO NOT EDIT MANUALLY */
window.BACKEND_URL = "${BACKEND_URL}";
EOF
    echo " Frontend/config.js generated with BACKEND_URL=${BACKEND_URL}"
else
    cat > Frontend/config.js <<EOF
/* Auto-generated by build.sh — BACKEND_URL not set, using auto-detection */
EOF
    echo "️  BACKEND_URL not set — frontend will use auto-detection"
fi

echo ""
echo " Build completed successfully!"
echo ""
