version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: monexamen_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Api@12345
      MYSQL_DATABASE: monexamen
      MYSQL_USER: jenos
      MYSQL_PASSWORD: Api@12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./Backend
    container_name: monexamen_backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=monexamen
      - DB_USER=jenos
      - DB_PASSWORD=Api@12345
      - SECRET_KEY=super-secret-key-pour-monexamen-jwt
    ports:
      - "5000:5000"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
    container_name: monexamen_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  backend_uploads:
